#!/bin/sh
# @author SJTU-XHW
# @file oh-install-hap

set -e

YES=0
PROJ_DIR=`pwd`
DEVICE_KEY=""
while getopts "yd:t:" arg
do
    case $arg in
    y)
        YES=1
        ;;
    d)
        PROJ_DIR=$OPTARG
        ;;
    t)
        DEVICE_KEY=$OPTARG
        ;;
    ?)
        echo "Unknown argument: $arg. Ignored."
        ;;
    esac
done

if [ "$YES" -eq 0 ]; then
    read -p "Make sure this is the root directory for the OH Project that you want: $PROJ_DIR (y/n) " CUR_ANS                                                                                     
else                                                                                                                                                                                          
    CUR_ANS="y"                                                                                                                                                                               
fi

cd $PROJ_DIR

if [ "$CUR_ANS" != "y" ]; then
    echo "Not confirmed."
    exit 0
fi

SHELL_DIR=$(dirname $(readlink -f "$0"))
SHELL_NAME=$(basename $(readlink -f "$0"))
BUNDLE_NAME=$(python3 ${SHELL_DIR}/print-bundlename.py `pwd`)
MODULE_NAME=$(python3 ${SHELL_DIR}/print-modulename.py `pwd`)

if [ -z "${DEVICE_KEY}" ]; then

hdc uninstall ${BUNDLE_NAME}
hdc install `pwd`/${MODULE_NAME}/build/default/outputs/default/${MODULE_NAME}-default-signed.hap

else

hdc -t ${DEVICE_KEY} uninstall ${BUNDLE_NAME}
hdc -t ${DEVICE_KEY} install `pwd`/${MODULE_NAME}/build/default/outputs/default/${MODULE_NAME}-default-signed.hap

fi
